#EnvLocal - 1
#EnvTest - 2
#EnvDev - 3
#EnvProd - 4
env_level: 4
storage_path: "/root/apps/pizzaland/pizzaland.db"
grpc:
  host: "0.0.0.0"
  port: 44044
  timeout: 5s
http:
  host: "0.0.0.0"
  port: 8080
  timeout: 5s
migration_path: "./migrations"